# 数据源配置
server:
  port: 8099

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.43.189:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
## Redis 配置
## Redis数据库索引（默认为0）
  redis:
    database: 0
    ## Redis服务器地址
    host: 192.168.43.200
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200

#######   此处有先后顺序，不然会报错
mybatis:
    config-location: classpath:mybatis-config.xml
    type-aliases-package: com.tienon.shop.data.domain
   mapper-locations: classpath:/com/tienon/shop/data/mapper/*.xml